language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
    - nightly

before_install:
    - pip uninstall setuptools -y

install:
    - python bootstrap.py --setuptools-version=20.2.2
    - ./bin/buildout install scripts crate test

before_script:
    - bin/flake8 --ignore=E,C901,F401,F821 --count src

script:
    - bin/coverage run bin/test

after_success:
    - PATH=$PATH:bin/ bin/codecov  # codecov executes coverage which needs to be in $PATH

notifications:
    email: false

sudo: false
addons:
  apt:
    packages:
        - oracle-java8-installer

matrix:
    allow_failures:
        - python: nightly
